# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the Odoo plugin for Dia !
# -*- coding: utf-8 -*-

{
    'name': "Libro de Inventario",

    'summary': """
        Libro de Inventario
        """,

    'description': """
        Libro de Inventario
    """,

    'author': "Softw & Hardw Solutions SSH",
    'website': "https://solutionssh.com/",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/master/odoo/addons/base/module/module_data.xml
    # for the full list
    'category': 'Contabilidad',
    'version': '0.1',

    # any module necessary for this one to work correctly
     "depends" : ['base','account','stock'],

    # always loaded
    'data': [
        'wizards/reporte_product.xml',
        'wizards/reporte_categoria.xml',
        'report/listado_movimiento_inventario.xml',
        'report/inventory_valuation_detail_template.xml',
        'security/ir.model.access.csv',
        ],  
    # only loaded in demonstration mode
    'demo': [
    ],
    'installable': True,
}

